#ifndef _ESP32_ALARM_BOARD_CONFIG_H_
#define _ESP32_ALARM_BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/adc.h>
#include "esp_codec_dev_defaults.h"

// Audio
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_INPUT_REFERENCE true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS GPIO_NUM_11
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_10
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_14

#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_PA_PIN GPIO_NUM_6

#define BUILTIN_LED_GPIO GPIO_NUM_48

// Buttons
#define KEY_AI_GPIO GPIO_NUM_0
#define KEY_BACK_GPIO GPIO_NUM_15
#define KEY_UP_GPIO GPIO_NUM_16

// #define TOUCH_BUTTON_GPIO GPIO_NUM_NC
// #define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
// #define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
// #define BACK_BUTTON_GPIO GPIO_NUM_NC
// #define VOICE_BUTTON_GPIO GPIO_NUM_NC

// Display
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_21
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define LCD_SCLK_PIN GPIO_NUM_39
#define LCD_MOSI_PIN GPIO_NUM_40
#define LCD_MISO_PIN GPIO_NUM_NC
#define LCD_DC_PIN GPIO_NUM_41
#define LCD_CS_PIN GPIO_NUM_42
#define LCD_RST_PIN GPIO_NUM_38

#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define ALARM_UI_SCREEN_W 320
#define ALARM_UI_SCREEN_H 240
#define ALARM_UI_STATUS_H 24
#define ALARM_UI_CONTENT_H 216

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_SPI_MODE 0

// Bluetooth serial
#define BL_TX_PIN GPIO_NUM_17
#define BL_RX_PIN GPIO_NUM_18

// Touch
#define TOUCH_I2C_SDA_PIN AUDIO_CODEC_I2C_SDA_PIN
#define TOUCH_I2C_SCL_PIN AUDIO_CODEC_I2C_SCL_PIN
#define TOUCH_INT_PIN GPIO_NUM_4
#define TOUCH_RST_PIN GPIO_NUM_8

// 4G
#define ML307C_RX_PIN GPIO_NUM_44
#define ML307C_TX_PIN GPIO_NUM_43
#define ML307C_DTR_PIN GPIO_NUM_NC

#define BATTERY_ADC_UNIT ADC_UNIT_1
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_0

// Backward-compatible aliases used by older code paths and generator output
#define DISPLAY_CLK_PIN LCD_SCLK_PIN
#define DISPLAY_MOSI_PIN LCD_MOSI_PIN
#define DISPLAY_DC_PIN LCD_DC_PIN
#define DISPLAY_CS_PIN LCD_CS_PIN
#define DISPLAY_RST_PIN LCD_RST_PIN
#define AUDIO_CODEC_I2C_PA_EN AUDIO_CODEC_PA_PIN
#define AUDIO_CODEC_PA_EN AUDIO_CODEC_PA_PIN

#define ESP32_ALARM_USE_NEW_UI 1

#endif // _ESP32_ALARM_BOARD_CONFIG_H_
