#ifndef _YHY_BOARD_CONFIG_H_
#define _YHY_BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_11
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_10
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_14

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define POWER_BUTTON_GPIO       GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_4
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_5

#define BUILTIN_LED_GPIO        GPIO_NUM_48

#define CHARGING_PIN            GPIO_NUM_6
#define CHARGING_STATUS_GPIO    GPIO_NUM_8

#define AI_MODE_GPIO            GPIO_NUM_15
#define NIGHT_LIGHT_GPIO        GPIO_NUM_7
#define BT_MODE_GPIO            GPIO_NUM_16
#define PA_ENABLE_GPIO          GPIO_NUM_21

#define EXTERNAL_SIM_DETECT_GPIO GPIO_NUM_38

#define TM1629A_STB_PIN GPIO_NUM_39
#define TM1629A_CLK_PIN GPIO_NUM_40
#define TM1629A_DIO_PIN GPIO_NUM_41

#define ML307C_DTR_PIN GPIO_NUM_NC
#define ML307C_TX_PIN  GPIO_NUM_43
#define ML307C_RX_PIN  GPIO_NUM_44
#define ML307C_RI_PIN  GPIO_NUM_NC

#define BT_TX_PIN  GPIO_NUM_17  // UART1_TXD（蓝牙模块RX）
#define BT_RX_PIN  GPIO_NUM_18  // UART1_RXD（蓝牙模块TX）

#define TM1629A_BOARD_TYPE_LICHUANG_DEV_ML307C 1

#endif // _YHY_BOARD_CONFIG_H_
